# features/add/tabs/manual/categories/data.py
from __future__ import annotations

CATEGORIES = [
    {"id": 101, "name": "食事",      "name_en": "Food",
     "subtitle": "飲み物、デザート、朝ご飯、昼ご飯、晩ご飯、その他",
     "subtitle_en": "Drinks, Dessert, Breakfast, Lunch, Dinner, Other",
     "icon": "silverware-fork-knife", "color": (0.26, 0.74, 0.42, 1)},
    {"id": 102, "name": "日常品",    "name_en": "Groceries",
     "subtitle": "日常品、食材、有料レジ袋、煙草、その他",
     "subtitle_en": "Daily goods, Ingredients, Plastic bags, Tobacco, Other",
     "icon": "cart-outline", "color": (0.21, 0.64, 0.86, 1)},
    {"id": 103, "name": "交通",      "name_en": "Transport",
     "subtitle": "電車、タクシー、バス、飛行機、その他",
     "subtitle_en": "Train, Taxi, Bus, Flight, Other",
     "icon": "train", "color": (0.51, 0.42, 0.96, 1)},
    {"id": 104, "name": "社交",      "name_en": "Social",
     "subtitle": "パーティー、プレゼント、儀式行事、その他",
     "subtitle_en": "Party, Gifts, Ceremonies, Other",
     "icon": "account-group-outline", "color": (0.96, 0.58, 0.35, 1)},
    {"id": 105, "name": "趣味",      "name_en": "Leisure",
     "subtitle": "イベント、映画、音楽、書籍、ゲーム",
     "subtitle_en": "Events, Movies, Music, Books, Games",
     "icon": "music", "color": (0.99, 0.76, 0.20, 1)},
    {"id": 106, "name": "教育",      "name_en": "Education",
     "subtitle": "授業料、参考書、試験料、塾",
     "subtitle_en": "Tuition, Reference books, Exam fees, Cram school",
     "icon": "school", "color": (0.96, 0.45, 0.53, 1)},
    {"id": 107, "name": "ファッション", "name_en": "Fashion",
     "subtitle": "服、アクセサリー、ジム、サロン、化粧品",
     "subtitle_en": "Clothes, Accessories, Gym, Salon, Cosmetics",
     "icon": "tshirt-crew", "color": (0.20, 0.80, 0.67, 1)},
    {"id": 108, "name": "医療",      "name_en": "Medical",
     "subtitle": "病院、薬、保険",
     "subtitle_en": "Hospital, Medicine, Insurance",
     "icon": "hospital-box-outline", "color": (0.96, 0.33, 0.33, 1)},
    {"id": 109, "name": "電話・ネット", "name_en": "Phone & Net",
     "subtitle": "携帯、固定電話、インターネット関連",
     "subtitle_en": "Mobile, Landline, Internet related",
     "icon": "cellphone", "color": (0.58, 0.64, 0.69, 1)},
    {"id": 110, "name": "家計費",    "name_en": "Utilities",
     "subtitle": "水道、電気、ガス",
     "subtitle_en": "Water, Electricity, Gas",
     "icon": "lightbulb-outline", "color": (0.99, 0.76, 0.20, 1)},
    {"id": 111, "name": "家",        "name_en": "Home",
     "subtitle": "家賃、ローン、家具、改造、保険",
     "subtitle_en": "Rent, Mortgage, Furniture, Renovation, Insurance",
     "icon": "home", "color": (1.00, 0.41, 0.26, 1)},
    {"id": 112, "name": "自動車",    "name_en": "Car",
     "subtitle": "ガソリン、駐車場、保険",
     "subtitle_en": "Gas, Parking, Insurance",
     "icon": "car", "color": (0.98, 0.58, 0.20, 1)},
    {"id": 199, "name": "その他",    "name_en": "Other",
     "subtitle": "手当、小遣い、未分類、前払金、チャージ、その他",
     "subtitle_en": "Allowance, Pocket money, Unsorted, Advance payment, Charge, Other",
     "icon": "dots-horizontal-circle-outline", "color": (0.70, 0.70, 0.70, 1)},
]
